config/routes.rb
Bars::Application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { sessions: "users/sessions" }

  root to: "bars#index"
  resources :bars do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :reviews do
    resources :votes do
      collection do
        post "upvote"
        post "downvote"
      end
    end
  end

  resources :admins, only: [:index, :create, :destroy]
  get "make_admin", to: "admins#make_admin"
  resources :users, only: [:index, :create, :destroy]
end

app/models/bar.rb
class Bar < ActiveRecord::Base
  include PgSearch
  multisearchable against: [:name, :description]

  belongs_to :user
  has_many :reviews

  validates :name, presence: true
  validates :description, presence: true
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true, length: { is: 2 }
  validates :zip, presence: true, numericality: true
  validates :phone, presence: true, length: { is: 10 }

  def self.search(input)
    bars = []
    results = PgSearch.multisearch(input)
    results.each do |result|
      if result[:searchable_type] == "Review"
        review = Review.find_by(id: result[:searchable_id])
        bar = Bar.find_by(id: review.bar_id)
        bars << bar
      else
        bar = Bar.find_by(id: result[:searchable_id])
        bars << bar
      end
    end
    bars = Kaminari.paginate_array(bars)
    bars
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :destroy]
  before_action :require_access, only: [:edit, :destroy]

  def index
    if params[:search]
      @bars = Bar.search(params[:search]).page(params[:page]).per(5)
    else
      @bars = Bar.all.order(:name).page(params[:page]).per(5)
    end
  end

  def show
    @bar = Bar.find(params[:id])
    @review = Review.new
    @reviews = @bar.reviews.order(created_at: :desc)
    @vote_total = Vote.group(:review_id).sum(:count)
  end

  def new
    @bar = Bar.new
  end

  def create
    @bar = Bar.new(bar_params)
    @bar.user = current_user

    if @bar.save
      flash[:notice] = "Bar added successfully."
      redirect_to bar_path(@bar)
    else
      flash[:error] = @bar.errors.full_messages.join(". ")
      render :new
    end
  end

  def edit
    @bar = Bar.find(params[:id])
  end

  def update
    @bar = Bar.find(params[:id])
    if @bar.update_attributes(bar_params)
      flash[:notice] = "Bar updated successfully."
      redirect_to bars_path(@bar)
    else
      flash[:error] = @bar.errors.full_messages.join(". ")
      render :edit
    end
  end

  def destroy
    current_user
    @bar = Bar.find(params[:id])
    if @bar.destroy && admin_signed_in?
      flash[:alert] = "#{@bar.name} has been deleted"
      redirect_to admins_path
    elsif @bar.destroy
      flash[:alert] = "#{@bar.name} has been deleted"
      redirect_to bars_path
    else
      flash[:alert] = "Error: Bar has not been deleted"
      redirect_to bar_path(@bar)
    end
  end

  private

  def bar_params
    params.require(:bar).permit(:name,
                                :description,
                                :user,
                                :street,
                                :city,
                                :state,
                                :zip,
                                :phone,
                                :website)
  end

  def require_access
    unless admin_signed_in?
    @bar = Bar.find(params[:id])
    @user = @bar.user
    if @user != current_user
      flash[:error] = "You do not have permission to make this change."
      redirect_to bar_path(@bar)
    end
  end
end
end

app/views/bars/edit.html.erb
<div class="container">
  <div class="column">

    <h1>Edit Bar</h1>

    <%= form_for(@bar) do |f| %>
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name %>

    <%= f.label :description, "Description:" %>
    <%= f.text_field :description %>

    <%= f.label :street, "Street:" %>
    <%= f.text_area :street %>

    <%= f.label :city, "City:" %>
    <%= f.text_area :city, value: "Boston" %>

    <%= f.label :state, "State:" %>
    <%= f.text_area :state, value: "MA" %>

    <%= f.label :zip, "Zip:" %>
    <%= f.text_area :zip %>

    <%= f.label :phone, "Phone:" %>
    <%= f.text_area :phone %>

    <%= f.label :website, "Website (Optional):" %>
    <%= f.text_area :website %>
    <%= f.submit "Update Bar" %>
    <% end %>
    </br>
    <div id="review">
      <div class="actions">
        <%= button_to "Delete Bar", bar_path(@bar), method: :delete, data: { confirm: "Are you sure?" } %>
        <%= button_to 'Cancel', bars_path, method: :get %>
      </div>
    </div>
  </div>
</div>

app/views/bars/index.html.erb
<div class="content-splash">
</br>
    <div class="row">
      <div id="review2">
      <h5>All Bars</h5>
        <ul id="bar-show">
          <% if @bars.length < 1 %>
            <li>"No results match your criteria"</li>
          <% else %>
            <% @bars.each do |bar| %>
              <li><%= link_to bar.name, bar_path(bar) %></li>
            <% end %>
          <% end %>
        </ul>
        <%= button_to "Add New Bar", new_bar_path, method: :get %>
      </div>
    </div>
  </div>
</div>
<div id="pagination">
<%= paginate @bars %>
</div>

app/views/bars/new.html.erb
<div class="row">
  <div class="column">
    </br>
    <div id="bar">
      <h1>Add Bar</h1>
        <%= form_for @bar do |f| %>
        <%= f.label :name, "Name:" %>
        <%= f.text_field :name %>

        <%= f.label :description, "Description:" %>
        <%= f.text_area :description %>

        <%= f.label :street, "Street:" %>
        <%= f.text_field :street %>

        <%= f.label :city, "City:" %>
        <%= f.text_field :city, value: "Boston" %>

        <%= f.label :state, "State:" %>
        <%= f.text_field :state, value: "MA" %>

        <%= f.label :zip, "Zip:" %>
        <%= f.text_field :zip %>

        <%= f.label :phone, "Phone:" %>
        <%= f.text_field :phone %>

        <%= f.label :website, "Website (Optional):" %>
        <%= f.text_field :website %>
        <div id="review">
          <div class="actions">
            <%= f.submit "Add Bar" %>
            <% end %>
            <%= button_to "View all bars", bars_path, method: :get %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/bars/show.html.erb
<div class="row">
  <div class="column">
    </br>
    <div id="bar">
        <h1><%= @bar.name %></h1>
        <li>
        <% if @reviews.any? %>
        <p1>Average Rating:</p1>
        <% rating_total = 0 %>
        <% @reviews.each do |review| %>
        <% rating_total += review.rating %>
        <% end %>
        <% average_rating = rating_total.to_f / @reviews.length %>
        <%= average_rating.round(1) %>
        <% end %>
        </li>
        <p1>Description: </p1><h2><%= @bar.description %></h2>
        <p1>Address: </p1><h2><%= @bar.street %>
        </br><%= @bar.state %>, <%= @bar.city %>, <%= @bar.zip %></h2>
        <p1>Phone: </p1><h2><%= @bar.phone %></h2>
            <% unless @bar.website.empty? %></h2>
        <p1>Website: </p1><h2><a href="https://<%= @bar.website%>" target="blank"><%= @bar.website%></a></h2>
            <% end %>
    </div>

      <% if @bar.user == current_user %>
      <div id="buttons-bar">
      </br>
        <%= button_to "Edit Bar", edit_bar_path(@bar), method: :get %>
        <%= button_to "Delete Bar", bar_path(@bar), method: :delete %>
      </div>
      <% end %>

       <% if @reviews.any? %>
     </br>
        <h4>Reviews of <%= @bar.name %></h4>
       <% end %>

     <% @reviews.each do |review| %>
     <div id="review">
       <div id="vote-<%= review.id %>" class="vote">
         <li href ="<%=upvote_review_votes_path(review)%>" class="upvote" id="<%= review.id %>"><%= button_to "Upvote", upvote_review_votes_path(review), method: :post %></li>
           <li class="vote-total" id="<%= review.id %>"><%= @vote_total[review.id] %></li>
         <li href ="<%=downvote_review_votes_path(review)%>"class="downvote" id="<%= review.id %>"><%= button_to "Downvote", downvote_review_votes_path(review), method: :post %></li>
       </div>

       <ul>
         </br><p1>Title:</p1> <%= review.title %>
         <li><p1>Review:</p1> <%= review.body %></li>
         <li id="rating-<%= review.id %>"><p1>Rating:</p1> <%= review.rating %></li>

         <% if review.user == current_user %>
         <div id="buttons-review">
           <li><%= button_to "Edit", edit_bar_review_path(@bar, review), method: :get %></li>
           <li><%= button_to "Delete", bar_review_path(@bar, review), method: :delete, data: { confirm: "Are you sure?" } %></li>
         </div>
         <% end %>
       </ul>
     </div>
   </br>
     <% end %>
   </br>
     <h4>Add Review for <%= @bar.name %></h4>
       <%= form_for [@bar, @review] do |f| %>
       <div class="field">
         <%= f.label :title, "Title:" %>
         <%= f.text_field :title %>
       </div>

        <div class="field">
          <%= f.label :body, "Review:" %>
          <%= f.text_area :body %>
        </div>

        <div class="field">
          <%= f.label :rating, "Rating:" %>
          <%= f.select :rating, options_for_select(1..5) %>
        </div>

        <div id="review">
          <div class="actions">
            <%= f.submit %>
            <% end %>
            <%= button_to "View All Bars", bars_path, method: :get %>
          </div>
        </div>
  </div>
</div>
<%= javascript_include_tag "application" %>