config/routes.rb
Bars::Application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { sessions: "users/sessions" }

  root to: "bars#index"
  resources :bars do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :reviews do
    resources :votes do
      collection do
        post "upvote"
        post "downvote"
      end
    end
  end

  resources :admins, only: [:index, :create, :destroy]
  get "make_admin", to: "admins#make_admin"
  resources :users, only: [:index, :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bars
  has_many :reviews

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    super
  end

  def create
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params["id"])
    @user.delete
    flash[:notice] = "User Deleted"
    redirect_to users_path
  end
end

app/views/users/index.html.erb
<div class="row">
  <div class="column">
    </br>
    <div id="bar">

      <h1>Users</h1>

      <% @users.each do |user| %>
        <%= user.email %>
          <div id='id-<%= user.id %>'>
            <%= button_to "Delete", user, method: :delete %>
            <%= link_to "Make Admin", make_admin_path(user_id: user.id) %>
          </div>
      <% end %>
    </div>
  </div>
</div>