config/routes.rb
Bars::Application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { sessions: "users/sessions" }

  root to: "bars#index"
  resources :bars do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :reviews do
    resources :votes do
      collection do
        post "upvote"
        post "downvote"
      end
    end
  end

  resources :admins, only: [:index, :create, :destroy]
  get "make_admin", to: "admins#make_admin"
  resources :users, only: [:index, :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="http://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>bevBOSTON | Find your new favorite watering hole in Boston.</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <div class="message">
    <% if flash.any? %>
      <div class="alert">
        <strong><%= flash[:notice] %></strong>
        <strong><%= flash[:error] %></strong>
        <strong><%= flash[:alert] %></strong>
      </div>
    <% end %>
  </div>

  <body>
    <%= yield %>
  </body>
  <div class="header">
    <div class="outer">
      <div class="dropdown">
        <button class="dropbtn"><img src="/assets/user.png"></button>
        <div class="dropdown-content">
          <%= link_to 'Sign up', new_user_registration_path unless current_user %>
          <%= link_to "Sign in", new_user_session_path unless current_user %>
          <%= link_to "Edit profile", edit_user_registration_path, method: :get if current_user %>
          <%= link_to "Sign out", destroy_user_session_path, method: :get if current_user %>
          <%= link_to "Admin Dashboard", admins_path, method: :get if admin_signed_in? %>
        </div>
      </div>
      <a href="/"><img src="/assets/logo.png"></a>
      <div class="box">
        <div class="container-1">
          <span class="icon">
            <i class="fa fa-search"></i>
          </span>
          <%= form_tag(bars_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search..." %>&nbsp;
            <%= submit_tag "Search" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</html>